
# Unscaled estimate forest plots

```{r, include=FALSE}
tableau10 <- c("#1F77B4","#FF7F0E","#2CA02C","#D62728",
               "#9467BD","#8C564B","#E377C2","#7F7F7F","#BCBD22","#17BECF")

library(tidyverse)
library(DT)

source("functions.R")




res = readRDS(here("results/adjusted_combined_arms_intervention_effects_unscaled_results_clean.RDS"))
res <- res %>% filter(measure=="ATE")
res = res %>% select(study, visit, contrast, category , biomarker, label_f,  est, cil, ciu, pval, pval_adj, sig, sigFDR)
res$biomarker = str_to_lower(res$biomarker)


  load(here("metadata/milk_component.Rdata"))

  
res_macro = res %>% filter(biomarker %in% c(all_milk_components$macro, "total carbohydrate"))
res_micro = res %>% filter(biomarker %in% c(all_milk_components$micro))
res_bvit = res %>% filter(biomarker %in% c(all_milk_components$bvit))
res_hmo = res %>% filter(biomarker %in% c(all_milk_components$hmo))
res_bioactives = res %>% filter(biomarker %in% c(all_milk_components$protein))
res_metabolomics = res %>% filter(biomarker %in% c(all_milk_components$metabolomics))


res_strat = readRDS(here("results/adjusted_intervention_effects_unscaled_results_clean.RDS"))
res_strat <- res_strat %>% filter(measure=="ATE")
res_strat = res_strat %>% select(study, visit, contrast, category , biomarker, label_f,  est, cil, ciu, pval, pval_adj, sig, sigFDR)
res_strat$biomarker = str_to_lower(res_strat$biomarker)

res_strat_macro = res_strat %>% filter(biomarker %in% c(all_milk_components$macro, "total carbohydrate"))
res_strat_micro = res_strat %>% filter(biomarker %in% c(all_milk_components$micro))
res_strat_bvit = res_strat %>% filter(biomarker %in% c(all_milk_components$bvit))
res_strat_hmo = res_strat %>% filter(biomarker %in% c(all_milk_components$hmo))
res_strat_bioactives = res_strat %>% filter(biomarker %in% c(all_milk_components$protein))
res_strat_metabolomics = res_strat %>% filter(biomarker %in% c(all_milk_components$metabolomics))



```



#### Macronutrients - combined arms

```{r, echo=FALSE}

forest_plot(res_macro)
clean_tab(res_macro)
```

#### Macronutrients - stratified arms

```{r, echo=FALSE}

forest_plot(res_strat_macro)
clean_tab(res_strat_macro)

```


#### Micronutrients - combined arms

```{r, echo=FALSE, fig.height=12}

forest_plot(res_micro)
clean_tab(res_micro)

```

#### Micronutrients - stratified arms

```{r, echo=FALSE, fig.height=12}

#forest_plot(read.csv(here("results/subsetted results/primary_micro_arm_strat.csv"), arm_strat=T)

```

#### B-vitamins - combined arms

```{r, echo=FALSE, fig.height=12}

forest_plot(res_bvit)
clean_tab(res_bvit)


```

#### B-vitamins - stratified arms

```{r, echo=FALSE, fig.height=12}

#forest_plot(read.csv(here("results/subsetted results/primary_bvit_arm_strat.csv"), arm_strat=T)

```


#### HMOs - combined arms

```{r, echo=FALSE, fig.height=12}

forest_plot(res_hmo)
clean_tab(res_hmo)
```


#### HMOs - stratified arms

```{r, echo=FALSE, fig.height=12}

#forest_plot(read.csv(here("results/subsetted results/secondary_hmo_arm_strat.csv"), arm_strat=T)

```

#### Bioactives - combined arms

```{r, echo=FALSE, fig.height=12}

forest_plot(res_bioactives)
clean_tab(res_bioactives)

```



#### Bioactives - stratified arms

```{r, echo=FALSE, fig.height=12}

#forest_plot(read.csv(here("results/subsetted results/secondary_bioactives_arm_strat.csv"), arm_strat=T)

```

